/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnosRouteImport } from './routes/turnos'
import { Route as ProfesionalesRouteImport } from './routes/profesionales'
import { Route as ExploraRouteImport } from './routes/explora'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TurnosRoute = TurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesRoute = ProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploraRoute = ExploraRouteImport.update({
  id: '/explora',
  path: '/explora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explora': typeof ExploraRoute
  '/profesionales': typeof ProfesionalesRoute
  '/turnos': typeof TurnosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explora': typeof ExploraRoute
  '/profesionales': typeof ProfesionalesRoute
  '/turnos': typeof TurnosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explora': typeof ExploraRoute
  '/profesionales': typeof ProfesionalesRoute
  '/turnos': typeof TurnosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/explora' | '/profesionales' | '/turnos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/explora' | '/profesionales' | '/turnos'
  id: '__root__' | '/' | '/admin' | '/explora' | '/profesionales' | '/turnos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ExploraRoute: typeof ExploraRoute
  ProfesionalesRoute: typeof ProfesionalesRoute
  TurnosRoute: typeof TurnosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnos': {
      id: '/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof TurnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales': {
      id: '/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explora': {
      id: '/explora'
      path: '/explora'
      fullPath: '/explora'
      preLoaderRoute: typeof ExploraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExploraRoute: ExploraRoute,
  ProfesionalesRoute: ProfesionalesRoute,
  TurnosRoute: TurnosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
