/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnosRouteImport } from './routes/turnos'
import { Route as ProfesionalesRouteImport } from './routes/profesionales'
import { Route as IndexRouteImport } from './routes/index'

const TurnosRoute = TurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesRoute = ProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profesionales': typeof ProfesionalesRoute
  '/turnos': typeof TurnosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profesionales': typeof ProfesionalesRoute
  '/turnos': typeof TurnosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profesionales': typeof ProfesionalesRoute
  '/turnos': typeof TurnosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profesionales' | '/turnos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profesionales' | '/turnos'
  id: '__root__' | '/' | '/profesionales' | '/turnos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfesionalesRoute: typeof ProfesionalesRoute
  TurnosRoute: typeof TurnosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnos': {
      id: '/turnos'
      path: '/turnos'
      fullPath: '/turnos'
      preLoaderRoute: typeof TurnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales': {
      id: '/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfesionalesRoute: ProfesionalesRoute,
  TurnosRoute: TurnosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
